DROP TABLE Event CASCADE CONSTRAINTS;
DROP TABLE RolesP CASCADE CONSTRAINTS;
DROP TABLE EmergencyDrill CASCADE CONSTRAINTS;
DROP TABLE EmergenBodies CASCADE CONSTRAINTS;
DROP TABLE EvDebriefing CASCADE CONSTRAINTS;
DROP TABLE TakingPart CASCADE CONSTRAINTS;
DROP TABLE TeamP CASCADE CONSTRAINTS;
DROP TABLE Worker CASCADE CONSTRAINTS;
DROP TABLE ActIn CASCADE CONSTRAINTS;
DROP TABLE Reoprt CASCADE CONSTRAINTS;
DROP TABLE Practicing CASCADE CONSTRAINTS;

