-- SELECT עבור הטבלה ACTIN
SELECT * FROM ACTIN;

-- SELECT עבור הטבלה CATEGORY
SELECT * FROM CATEGORY;

-- SELECT עבור הטבלה DONATION
SELECT * FROM DONATION;

-- SELECT עבור הטבלה DONOR
SELECT * FROM DONOR;

-- SELECT עבור הטבלה EMERGENBODIES
SELECT * FROM EMERGENBODIES;

-- SELECT עבור הטבלה EMERGENCYDRILL
SELECT * FROM EMERGENCYDRILL;

-- SELECT עבור הטבלה EVDEBRIEFING
SELECT * FROM EVDEBRIEFING;

-- SELECT עבור הטבלה EVENT
SELECT * FROM EVENT;

-- SELECT עבור הטבלה ITEM
SELECT * FROM ITEM;

-- SELECT עבור הטבלה LOCATION
SELECT * FROM LOCATION;

-- SELECT עבור הטבלה MAINTENANCE
SELECT * FROM MAINTENANCE;

-- SELECT עבור הטבלה OPERATION
SELECT * FROM OPERATION;

-- SELECT עבור הטבלה OPERATOR
SELECT * FROM OPERATOR;

-- SELECT עבור הטבלה PRACTICING
SELECT * FROM PRACTICING;

-- SELECT עבור הטבלה REOPRT
SELECT * FROM REOPRT;

-- SELECT עבור הטבלה REOPRTEV
SELECT * FROM REOPRTEV;

-- SELECT עבור הטבלה ROLESP
SELECT * FROM ROLESP;

-- SELECT עבור הטבלה TAKINGPART
SELECT * FROM TAKINGPART;

-- SELECT עבור הטבלה TEAMP
SELECT * FROM TEAMP;

-- SELECT עבור הטבלה WORKER
SELECT * FROM WORKER;

-- SELECT עבור הטבלה MAINTO
SELECT * FROM MAINTO;

-- SELECT עבור הטבלה DONERTO
SELECT * FROM DONERTO;

-- SELECT עבור הטבלה DRILLCATEGORYOF
SELECT * FROM DRILLCATEGORYOF;
